window.DECK_SLIDES = [
    { id: 'cover', theme: 'image' },
    { id: 'scene', theme: 'image' },
    { id: 'loop', theme: 'paper' },
    { id: 'difference', theme: 'dark' },
    { id: 'boundary', theme: 'paper' },
    { id: 'weapons', theme: 'image' },
    { id: 'loot', theme: 'dark' },
    { id: 'efficiency', theme: 'paper' },
    { id: 'scale', theme: 'dark' },
    { id: 'performance', theme: 'paper' },
    { id: 'mobile', theme: 'paper' },
    { id: 'expansion', theme: 'dark' },
    { id: 'evidence', theme: 'paper' },
    { id: 'milestones', theme: 'dark' }
];

window.DECK_I18N = {
    ko: {
        ui_page_title: 'Tomato Splatter | Jumpstart 제안', ui_lang_group: '언어 선택', ui_prev: '이전', ui_next: '다음', ui_fullscreen: '전체화면', ui_fullscreen_exit: '전체화면 종료', ui_deck_label: 'Tomato Splatter Jumpstart 제안 슬라이드', ui_dot: '{{n}}번 슬라이드로 이동', ui_dot_appendix: '부록 {{n}}번 슬라이드로 이동', ui_slide_position: '{{current}} / {{total}} 슬라이드', ui_appendix: '부록', ui_appendix_position: '부록 {{current}} / {{total}}',
        cover_kicker: 'ROBLOX JUMPSTART 제안', cover_lead: '직접 조작과 자동 전투를 넘나들며 토마토 무리를 쓸어버리고, 쏟아지는 전리품으로 나만의 장비 조합을 만드는 핵앤슬래시 파밍 게임', concept_caption: '콘셉트 비주얼 — 최종 게임플레이 아님',
        scene_title: '토마토 무리 한가운데로 뛰어들어 휠윈드를 돌린다.\n몰려드는 적을 학살하고 전리품을 쓸어 담는다.\n직접 확인하고 가공해 장비를 강화하며 성장한다.', scene_callout_1: '무리', scene_callout_2: '연쇄 타격', scene_callout_3: '희귀 드랍', scene_emotion: '압도 · 발견 · 성장',
        loop_title: '적을 쓰러뜨려 전리품과 재료를 모은다.\n쓸 만한 장비는 챙기고, 모은 재료로 더 나은 장비를 만든다.', loop_1: '전투', loop_1_sub: '휠윈드로 몰려드는 적을 쓸어버린다', loop_2: '전리품', loop_2_sub: '획득한 아이템을 살펴 장착할 것과 판매할 것을 고른다', loop_3: '장비', loop_3_sub: '모은 재료로 더 나은 장비를 제작한다', loop_bottom: '장비를 갖추면 더 깊은 웨이브와 강한 적에게 도전할 수 있다',
        difference_title: '휠윈드로 토마토 무리를 쓸어버리면,\n화면 가득 케첩이 튀고 전리품이 쏟아진다.', difference_1: '휠윈드 궤적', difference_1_sub: '밝은 궤적으로 공격이 닿는 범위를 바로 알 수 있다', difference_2: '케첩 폭발', difference_2_sub: '토마토를 맞히면 케첩과 과육이 사방으로 튄다', difference_3: '쏟아지는 전리품', difference_3_sub: '평범한 재료부터 전설 장비까지, 다음에 무엇이 떨어질지 몰라 계속 사냥하게 된다',
        boundary_title: '직접 싸우고 싶을 때는 바로 개입하고,\n반복 사냥은 자동 전투에 맡긴다.', boundary_lead: '이동을 입력하면 전투에 바로 개입할 수 있다. 반복 사냥은 자동 전투가 이어가지만, 장비와 성장 방향은 플레이어가 직접 결정한다.', boundary_auto: '직접 조작 ↔ 자동 전투', boundary_auto_1: '이동 입력으로 즉시 개입', boundary_auto_2: '적 무리 자동 추적', boundary_auto_3: '휠윈드 반복 공격', boundary_auto_4: '전리품 획득', boundary_transfer: '전리품 확인', boundary_player: '직접 선택', boundary_player_1: '장비 비교', boundary_player_2: '강화 · 합성 · 분해', boundary_player_3: '보석 장착', boundary_player_4: '성장 포인트 배분 · 펫 합성',
        weapons_title: '무기가 바뀌면, 손맛도 달라진다', weapons_lead: '무기의 공격 속도와 범위가 달라지면, 같은 전투에서도 노리는 적과 싸우는 방식이 달라진다.', weapons_feel_1: '묵직한 일격', weapons_feel_1_sub: '강한 적에게 큰 충격을 준다', weapons_feel_2: '시원한 휩쓸기', weapons_feel_2_sub: '몰려든 적 무리를 한꺼번에 정리한다', weapons_feel_3: '빠른 연속 타격', weapons_feel_3_sub: '엘리트와 보스에게 공격을 집중한다',
        loot_title: '전리품이 쏟아지고,\n그 안에서 다음 빌드가 시작된다.', loot_lead: '같은 종류의 무기라도 등급과 랜덤 옵션이 다르다. 지금 쓸 장비와 빌드에 필요한 재료를 가려 다음 빌드를 준비한다.', loot_step_1: '등급과 옵션이 다른 전리품', loot_step_1_sub: '평범한 재료부터 희귀한 무기까지 서로 다른 가치로 떨어진다', loot_step_2: '쓸 것과 남길 것을 고른다', loot_step_2_sub: '현재 장비와 빌드에 맞춰 아이템을 직접 비교한다', loot_step_3: '빌드를 완성해 다음 전투를 바꾼다', loot_step_3_sub: '장착과 보석, 크래프팅으로 새로운 빌드를 만든다', loot_rule: '아이템 하나를 얻는 재미가, 빌드를 바꾸고 다시 사냥하는 이유로 이어진다.',
        efficiency_title: '모은 것은 남고,\n도전은 더 깊어진다.', efficiency_lead: '전투에서 쓰러져도 장비와 재화는 잃지 않는다. 웨이브만 처음부터 다시 시작하며, 강해진 만큼 이전보다 더 깊은 구간에 도달한다.', efficiency_keep: '쓰러져도 남는다', efficiency_keep_sub: '획득한 무기와 Coin, 아이템은 그대로 보유한다.', efficiency_keep_items: '무기 · Coin · 획득 아이템', efficiency_reset: '웨이브만 돌아간다', efficiency_reset_sub: '진행 위치만 초기화되고, 같은 전투장에 다시 도전한다.', efficiency_reset_items: '진행 위치 · 소요 시간', efficiency_deeper: '더 깊이 들어간다', efficiency_deeper_sub: '강해진 만큼 높은 웨이브에 오래 머물고, 더 좋은 전리품을 얻는다.', efficiency_deeper_items: '깊은 웨이브 · 높은 파밍 효율', efficiency_rule: '전투에서 막힌 지점이, 다음 무기를 찾을 이유가 된다.',
        scale_title: '새로운 맵이 없어도,\n새로운 옵션이 파밍 목표를 만든다.', scale_lead: '같은 무기도 등급, 랜덤 옵션, 보석과 크래프팅 조합에 따라 성능과 쓰임이 달라진다. 원하는 빌드를 완성하는 과정이 반복 플레이를 만든다.', scale_step_1: '장비가 쏟아진다', scale_step_1_sub: '무기마다 등급과 랜덤 옵션이 다르게 붙는다.', scale_step_2: '필요한 옵션을 고른다', scale_step_2_sub: '현재 빌드에 맞는 장비와 재료를 가려낸다.', scale_step_3: '빌드를 다듬는다', scale_step_3_sub: '보석과 크래프팅으로 부족한 성능을 보완한다.', scale_step_4: '새로운 빌드를 완성한다', scale_step_4_sub: '빌드에 따라 전투 방식과 다음 파밍 목표가 달라진다.', scale_repeat: '하나의 전투장이 무기 종류, 등급, 옵션과 조합에 따라 수많은 파밍 목표로 확장된다.', scale_test_title: '완성한 빌드는 두 전장에서 직접 확인한다', scale_test_pve: '더 깊은 웨이브와 보스', scale_test_pve_sub: '전투력과 파밍 효율을 확인한다', scale_test_pvp: '선택형 플레이어 대전', scale_test_pvp_sub: '다른 빌드와 겨루며 장비 효능을 체감한다',
        performance_title: '많은 적이 몰려와도,\n모바일에서 전투가 끊기지 않게 설계한다.', performance_lead: '전투의 밀도와 타격감은 유지하고, 플레이에 필요하지 않은 연산을 줄인다.', perf_target: '화면에 남겨야 하는 것', perf_target_sub: '이 게임의 인상을 만드는 전투 요소는 그대로 보여준다.', perf_target_1: '몰려드는 적', perf_target_2: '연쇄 타격', perf_target_3: '케첩 폭발', perf_target_4: '희귀 드랍', perf_bridge: '플레이에 필요하지 않은 연산을 줄인다', perf_1: '필요한 공간만 불러온다', perf_1_sub: '현재 전투에 필요한 월드만 화면에 표시한다.', perf_2: '필요한 적만 움직인다', perf_2_sub: '실제 전투에 참여하는 적을 중심으로 연산한다.', perf_3: '화면 효과를 조절한다', perf_3_sub: '전투 상황과 기기 성능에 맞춰 이펙트의 양을 조절한다.', perf_verify_bridge: '대표 환경에서 직접 확인한다', perf_test: '실제 성능을 확인한다', perf_test_1: '대표 모바일 기기', perf_test_2: '8인 서버 환경', performance_rule: '보이는 전투의 밀도는 유지하고, 보이지 않는 부담을 줄인다.',
        mobile_title: '고르는 재미는 남기고,\n반복 조작은 줄인다.', mobile_lead: '아이템이 많아져도 무엇을 남기고 사용할지는 직접 고른다. 인터페이스는 그 결정을 빠르게 실행할 수 있게 돕는다.', mobile_step_1: '한눈에 비교한다', mobile_step_1_sub: '현재 장비와 새로 얻은 아이템의 차이를 한 화면에서 확인한다.', mobile_step_2: '직접 고른다', mobile_step_2_sub: '남길 장비와 정리할 아이템을 플레이어가 선택한다.', mobile_step_3: '선택한 것만 한 번에 처리한다', mobile_step_3_sub: '같은 작업을 여러 번 누르지 않고, 선택한 항목에 한 번에 실행한다.', mobile_rule: '게임이 대신 고르지 않는다. 플레이어의 결정을 빠르게 실행할 뿐이다.',
        expansion_title: '업데이트는 맵의 양보다,\n파밍의 가능성을 넓힌다.', expansion_lead: '새로운 무기와 랜덤 옵션, 보석과 제작식을 추가하면 기존 전투장에서도 새로운 빌드와 파밍 목표가 생긴다.', exp_1: '새로운 무기 효과', exp_1_sub: '공격 방식과 손맛이 달라진다', exp_2: '새로운 랜덤 옵션', exp_2_sub: '노릴 수 있는 성능 조합이 늘어난다', exp_center: '아이템 메타', exp_center_sub: '파밍 목표를 확장하는 업데이트', exp_3: '새로운 보석과 제작식', exp_3_sub: '기존 아이템에도 새로운 가치가 생긴다', exp_4: '변화하는 PvP 빌드', exp_4_sub: '새로운 빌드를 시험하고 대응한다', expansion_rule: '새로운 지역과 보스도 추가하되, 반복 플레이를 신규 맵 공급에만 의존하지 않는다.',
        evidence_title: '전작에서 만든 전투 경험을 바탕으로,\n더 깊은 파밍과 성장의 재미를 설계합니다.', evidence_lead: 'Tomato Splatter Simulator는 2026년 4월 Roblox에 출시되었습니다.', evidence_capture: '전작 라이브 빌드의 실제 플레이 화면', evidence_verified: '전작에서 구현한 것', evidence_1: '토마토 무리를 연속으로 타격하는 전투', evidence_2: '무기·피격·케첩 이펙트', evidence_3: '저장·상품·라이브 운영 기반', evidence_next: '신작에서 더하는 것', evidence_next_1: '웨이브와 보스 전투', evidence_next_2: '다양한 무기와 파밍', evidence_next_3: '빌드에 따른 전투 방식의 변화', evidence_next_4: '장기 성장과 수집', evidence_art: '20년 경력 아트 디렉터가 모델링·애니메이션·VFX 제작을 이끈다.',
        milestone_title: '핵심 전투부터 아이템 메타와 PvP까지,\n검증한 만큼 단계적으로 넓힌다.', milestone_lead: '하나의 전투장에서 전투를 확인한 뒤, 파밍 구조와 PvP를 차례로 연결하고 출시 범위로 확장한다.', plan_time_1: '1–3개월', plan_time_2: '4–6개월', plan_time_3: '7–9개월', plan_time_4: '10–12개월', plan_total_1_at: '6개월', plan_total_1: '아이템 파밍 루프 검증까지', plan_total_2_at: '12개월', plan_total_2: '출시 · 라이브 확장까지', plan_1: '핵심 전투 검증', plan_1_sub: '전투장 한 곳에서 타격감, 직접·자동 전투와 모바일 성능을 확인한다.', plan_2: '아이템 파밍 루프', plan_2_sub: '등급, 랜덤 옵션, 보석과 크래프팅이 하나의 성장 흐름으로 이어지는지 검증한다.', plan_3: 'PvE·PvP 빌드 검증', plan_3_sub: '완성한 빌드의 차이가 PvE와 선택형 PvP에서 분명하게 체감되는지 확인한다.', plan_4: '출시·라이브 확장', plan_4_sub: '무기, 옵션과 제작식을 출시 범위까지 확장하고 첫 라이브 업데이트를 준비한다.', milestone_note: '각 단계마다 검증용 테스트 게임을 출시해 실제 플레이 데이터를 확보하고, 그 결과를 근거로 개선 방향과 다음 단계의 확장 범위를 정합니다. 총 개발 기간 12개월을 기준으로, 단계별 배분은 담당자의 작업량과 가용 일정을 검토한 뒤 조정합니다.', final_line: '토마토 무리를 쓸어버리는 순간의 쾌감에서,\n오래 파고드는 파밍의 재미까지.',
        alt_hero: '토마토 무리 한가운데에서 휠윈드를 사용하는 플레이어 콘셉트 비주얼', alt_crop_whirlwind: '밝고 큰 휠윈드 궤적', alt_crop_ketchup: '토마토가 케첩처럼 터지는 장면', alt_crop_loot: '바닥에 쏟아진 전리품과 보라색 빛기둥으로 표시된 희귀 무기', alt_weapons: '망치, 도끼, 검으로 서로 다른 타격감을 보여주는 3분할 전투 콘셉트 비주얼', alt_loot: '전리품이 쏟아지고 여러 무기 중 새 무기를 고르는 과정을 보여주는 콘셉트 비주얼'
    },
    en: {
        ui_page_title: 'Tomato Splatter | Jumpstart Proposal', ui_lang_group: 'Language', ui_prev: 'Previous', ui_next: 'Next', ui_fullscreen: 'Fullscreen', ui_fullscreen_exit: 'Exit fullscreen', ui_deck_label: 'Tomato Splatter Jumpstart proposal slides', ui_dot: 'Go to slide {{n}}', ui_dot_appendix: 'Go to appendix slide {{n}}', ui_slide_position: 'Slide {{current}} of {{total}}', ui_appendix: 'Appendix', ui_appendix_position: 'Appendix {{current}} of {{total}}',
        cover_kicker: 'ROBLOX JUMPSTART PROPOSAL', cover_lead: 'A hack-and-slash loot game where you switch between direct control and auto-combat, clear tomato hordes, and build your own gear out of what drops.', concept_caption: 'CONCEPT VISUAL — NOT FINAL GAMEPLAY',
        scene_title: 'Dive into the heart of the horde, Whirlwind spinning.\nSlaughter everything that closes in and take the loot.\nThen sort it, upgrade it, and grow stronger.', scene_callout_1: 'HORDES', scene_callout_2: 'CHAIN HITS', scene_callout_3: 'RARE DROP', scene_emotion: 'DOMINANCE · DISCOVERY · GROWTH',
        loop_title: 'Defeat enemies to collect loot and materials.\nEquip what you need, sell what you don’t, and craft better gear.', loop_1: 'COMBAT', loop_1_sub: 'Cut through incoming hordes with Whirlwind', loop_2: 'LOOT', loop_2_sub: 'Review each item and choose what to equip or sell', loop_3: 'GEAR', loop_3_sub: 'Use collected materials to craft better gear', loop_bottom: 'Better gear lets you push into deeper waves and take on tougher enemies',
        difference_title: 'When Whirlwind cuts through a tomato horde,\nketchup splashes across the screen and loot spills onto the ground.', difference_1: 'WHIRLWIND TRAIL', difference_1_sub: 'A bright trail shows exactly how far the attack reaches', difference_2: 'KETCHUP BURST', difference_2_sub: 'Tomatoes burst into ketchup and pulp when hit', difference_3: 'LOOT DROPS', difference_3_sub: 'From basic materials to legendary gear, you never know what will drop next',
        boundary_title: 'Take direct control when you want.\nLet auto-combat carry the hunt when you don’t.', boundary_lead: 'Move, and you’re back in the fight instantly. Auto-combat handles the grind, but every gear and progression call is still yours.', boundary_auto: 'DIRECT ↔ AUTO', boundary_auto_1: 'Step in with movement input', boundary_auto_2: 'Track nearby hordes', boundary_auto_3: 'Repeat Whirlwind attacks', boundary_auto_4: 'Pick up loot', boundary_transfer: 'REVIEW LOOT', boundary_player: 'YOU DECIDE', boundary_player_1: 'Compare gear', boundary_player_2: 'Upgrade · merge · dismantle', boundary_player_3: 'Socket gems', boundary_player_4: 'Spend points · merge pets',
        weapons_title: 'A new weapon changes how combat feels.', weapons_lead: 'Attack speed and reach decide which enemies you go after and how a fight plays out.', weapons_feel_1: 'HEAVY IMPACT', weapons_feel_1_sub: 'Land a powerful hit on tougher enemies', weapons_feel_2: 'WIDE SWEEP', weapons_feel_2_sub: 'Clear the horde in a single arc', weapons_feel_3: 'RAPID STRIKES', weapons_feel_3_sub: 'Focus sustained attacks on elites and bosses',
        loot_title: 'Loot spills out.\nThe next build starts there.', loot_lead: 'Two weapons of the same type can still roll different rarities and affixes. Decide what to equip now and what to save for your next build.', loot_step_1: 'DIFFERENT RARITIES & AFFIXES', loot_step_1_sub: 'Everything from common materials to rare weapons, each with its own value', loot_step_2: 'CHOOSE WHAT MATTERS', loot_step_2_sub: 'Compare each item against your current gear and build', loot_step_3: 'BUILD FOR THE NEXT FIGHT', loot_step_3_sub: 'Equip, socket, and craft gear into a new build', loot_rule: 'Finding one item can change your build—and give you a reason to hunt again.',
        efficiency_title: 'Keep what you earn.\nPush deeper next time.', efficiency_lead: 'Dying never costs you gear or currency. Only wave progress resets, so every upgrade helps the next run reach farther than the last.', efficiency_keep: 'WHAT YOU KEEP', efficiency_keep_sub: 'Weapons, Coin, and collected items stay with you.', efficiency_keep_items: 'WEAPONS · COIN · COLLECTED ITEMS', efficiency_reset: 'ONLY THE WAVE RESETS', efficiency_reset_sub: 'Your position resets and you begin the arena climb again.', efficiency_reset_items: 'POSITION · TIME', efficiency_deeper: 'THE NEXT RUN GOES DEEPER', efficiency_deeper_sub: 'More power means more time in higher waves and better loot.', efficiency_deeper_items: 'DEEPER WAVES · BETTER FARMING', efficiency_rule: 'Wherever your run ends is the reason to go find a better weapon.',
        scale_title: 'New affixes create new farming goals—\neven without a new map.', scale_lead: 'The same weapon can perform very differently depending on rarity, random affixes, gems, and crafting. Completing the build you want is what keeps the hunt going.', scale_step_1: 'LOOT DROPS', scale_step_1_sub: 'Every weapon rolls with its own rarity and random affixes.', scale_step_2: 'PICK THE RIGHT AFFIXES', scale_step_2_sub: 'Sort out the gear and materials that fit your current build.', scale_step_3: 'REFINE THE BUILD', scale_step_3_sub: 'Use gems and crafting to fill the gaps in the build.', scale_step_4: 'COMPLETE A NEW BUILD', scale_step_4_sub: 'A new build changes both combat and the next farming goal.', scale_repeat: 'Weapon types, rarities, affixes, and combinations turn one arena into many different farming goals.', scale_test_title: 'PUT THE FINISHED BUILD TO THE TEST', scale_test_pve: 'DEEPER WAVES & BOSSES', scale_test_pve_sub: 'Measure combat power and farming efficiency', scale_test_pvp: 'OPTIONAL PLAYER COMBAT', scale_test_pvp_sub: 'Face other builds and see how your gear stacks up',
        performance_title: 'Design for smooth mobile combat,\neven when the horde closes in.', performance_lead: 'Preserve combat density and impact while reducing work the player never needs to see.', perf_target: 'WHAT PLAYERS SHOULD STILL SEE', perf_target_sub: 'Preserve the combat elements that define the game.', perf_target_1: 'DENSE HORDES', perf_target_2: 'CHAIN HITS', perf_target_3: 'KETCHUP BURSTS', perf_target_4: 'RARE DROPS', perf_bridge: 'Reduce work that does not affect play', perf_1: 'LOAD ONLY THE AREA IN PLAY', perf_1_sub: 'Show only the world needed for the current fight.', perf_2: 'SIMULATE ONLY ACTIVE ENEMIES', perf_2_sub: 'Focus simulation on enemies taking part in combat.', perf_3: 'ADJUST ON-SCREEN EFFECTS', perf_3_sub: 'Scale effect density to the fight and the device.', perf_verify_bridge: 'Check it in representative conditions', perf_test: 'VERIFY REAL PERFORMANCE', perf_test_1: 'Representative mobile devices', perf_test_2: '8-player server environment', performance_rule: 'Preserve the density players see. Reduce the load they do not.',
        mobile_title: 'Keep the fun of choosing.\nCut the repetitive taps.', mobile_lead: 'Even when your inventory fills up, you decide what to keep and use. The interface just makes those decisions faster to act on.', mobile_step_1: 'COMPARE AT A GLANCE', mobile_step_1_sub: 'See the difference between equipped gear and a new item on one screen.', mobile_step_2: 'CHOOSE FOR YOURSELF', mobile_step_2_sub: 'You decide what to keep and what to clear out.', mobile_step_3: 'APPLY TO ALL SELECTED', mobile_step_3_sub: 'Apply the same action to selected items without repeating every tap.', mobile_rule: 'You make the call. The interface just makes it quick.',
        expansion_title: 'Updates expand the loot game—\nnot just the map count.', expansion_lead: 'New weapons, random affixes, gems, and recipes create fresh builds and farming goals inside arenas players already know.', exp_1: 'NEW WEAPON EFFECTS', exp_1_sub: 'Different attacks and combat feel', exp_2: 'NEW RANDOM AFFIXES', exp_2_sub: 'More performance combinations to chase', exp_center: 'ITEM META', exp_center_sub: 'Updates that expand farming goals', exp_3: 'NEW GEMS & RECIPES', exp_3_sub: 'New value for existing items', exp_4: 'AN EVOLVING PvP META', exp_4_sub: 'Test new builds and learn how to counter them', expansion_rule: 'New regions and bosses still arrive, but replayability does not depend on a constant supply of maps.',
        evidence_title: 'Building on the combat experience of our previous title,\nwe are designing deeper loot and progression.', evidence_lead: 'Tomato Splatter Simulator launched on Roblox in April 2026.', evidence_capture: 'Actual gameplay from the previous live build', evidence_verified: 'BUILT IN THE PREVIOUS TITLE', evidence_1: 'Combat against dense tomato hordes', evidence_2: 'Weapon, hit, and ketchup effects', evidence_3: 'Data, commerce, and live-ops foundation', evidence_next: 'ADDED IN THE NEW TITLE', evidence_next_1: 'Waves and boss fights', evidence_next_2: 'A wider weapon hunt', evidence_next_3: 'Builds that change how combat plays', evidence_next_4: 'Long-term progression and collection', evidence_art: 'A 20-year veteran art director leads modeling, animation, and VFX production.',
        milestone_title: 'From core combat to item meta and PvP,\nwe expand only after each step works.', milestone_lead: 'Start with combat in one arena, then connect the loot system and PvP before expanding to launch scope.', plan_time_1: 'M1–M3', plan_time_2: 'M4–M6', plan_time_3: 'M7–M9', plan_time_4: 'M10–M12', plan_total_1_at: '6 MONTHS', plan_total_1: 'to a validated farming loop', plan_total_2_at: '12 MONTHS', plan_total_2: 'to launch and live expansion', plan_1: 'CORE COMBAT', plan_1_sub: 'Validate impact, direct and auto-combat, and mobile performance in one arena.', plan_2: 'ITEM FARMING LOOP', plan_2_sub: 'Validate rarity, random affixes, gems, and crafting as one progression flow.', plan_3: 'PvE & PvP BUILDS', plan_3_sub: 'Confirm that finished builds feel meaningfully different in PvE and optional PvP.', plan_4: 'LAUNCH & LIVE EXPANSION', plan_4_sub: 'Expand weapons, affixes, and recipes to launch scope and prepare the first live update.', milestone_note: 'Each stage ships a playable test build to Roblox, so real play data decides what we improve and how far the next stage expands. Based on a 12-month total, the split across stages will be adjusted after the team reviews workload and availability.', final_line: 'From the rush of clearing a tomato horde\nto the depth of a loot hunt worth returning to.',
        alt_hero: 'Concept visual of a player using Whirlwind in the middle of a tomato horde', alt_crop_whirlwind: 'A bright, wide Whirlwind trail', alt_crop_ketchup: 'Tomatoes bursting like ketchup', alt_crop_loot: 'Loot scattered across the ground with a rare weapon marked by a purple beam', alt_weapons: 'Three-panel combat concept showing different impact with a hammer, an axe, and a sword', alt_loot: 'Concept visual showing loot spilling out and choosing a new weapon from the haul'
    }
};
