// 신규 회사 소개 — 기존 company·nnn 문구를 재사용하고 KO/EN/JA로 작성.
// 지표는 제작 시점의 고정 스냅샷. 출처·기준일: docs/decks/company-intro/sources.md
// 기준: 2026-10-01T05:57:11.388Z (Roblox 공개 API 공식 갱신)
window.DECK_SLIDES = [
    {
        "id": "intro",
        "theme": "accent"
    },
    {
        "id": "metrics",
        "theme": "paper"
    },
    {
        "id": "live-games",
        "theme": "paper"
    },
    {
        "id": "game-design",
        "theme": "paper"
    },
    {
        "id": "ugc-rewards",
        "theme": "paper"
    },
    {
        "id": "ugc-creation",
        "theme": "paper"
    },
    {
        "id": "live-operations",
        "theme": "dark"
    },
    {
        "id": "technology",
        "theme": "paper"
    },
    {
        "id": "development",
        "theme": "paper"
    },
    {
        "id": "team",
        "theme": "paper",
        "backdropMarks": [
            {
                "image": "claude-icon.webp",
                "side": "left"
            },
            {
                "image": "chatgpt-icon.webp",
                "side": "right"
            }
        ],
        "avatars": [
            {
                "image": "people-oneshot.webp",
                "name": "ONESHOT"
            },
            {
                "image": "people-jeff.webp",
                "name": "JEFF",
                "featured": true
            },
            {
                "image": "people-papaslime.webp",
                "name": "PAPASLIME"
            }
        ]
    },
    {
        "id": "partnerships",
        "theme": "paper"
    },
    {
        "id": "ip-strategy",
        "theme": "dark"
    },
    {
        "id": "contact",
        "theme": "accent"
    },
    {
        "id": "history",
        "theme": "paper",
        "appendix": true
    },
    {
        "id": "metric-details",
        "theme": "paper",
        "appendix": true
    },
    {
        "id": "portfolio",
        "theme": "paper",
        "appendix": true
    },
    {
        "id": "ip-proposal",
        "theme": "paper",
        "appendix": true
    }
];

window.DECK_I18N = {
    "ko": {
        "ui_page_title": "NNN GAMES 회사 소개",
        "ui_prev": "이전",
        "ui_next": "다음",
        "ui_lang_group": "언어 선택",
        "ui_fullscreen": "전체화면",
        "ui_fullscreen_exit": "전체화면 종료",
        "ui_deck_label": "NNN GAMES 회사 소개 슬라이드",
        "ui_dot": "{{n}}번 슬라이드로 이동",
        "ui_dot_appendix": "부록 {{n}}번 슬라이드로 이동",
        "ui_slide_position": "{{current}} / {{total}} 슬라이드",
        "ui_appendix": "부록",
        "ui_appendix_position": "부록 {{current}} / {{total}}",
        "ui_slide_navigation": "슬라이드 선택",
        "meta_draft": "회사 소개 · 2026.10",
        "label_appendix": "부록",
        "label_visits": "누적 방문",
        "label_favorites": "즐겨찾기",
        "label_rating": "좋아요",
        "label_launch": "출시 월",
        "label_game": "게임",
        "label_current": "운영 중",
        "label_development": "개발 중",
        "label_concept": "개발 콘셉트",
        "label_expected": "출시 예정",
        "label_production": "UGC 제작 프로젝트",
        "source_current": "Roblox 공개 지표 · 2026.10.01 14:57 KST",
        "source_games": "운영 게임 6종 · Roblox 공개 지표 · 2026.10.01",
        "source_pipeline": "개발 중 · 등록된 출시 예정 월 기준 · 2026.10",
        "source_cases": "운영 게임의 플레이·보상 설계 사례",
        "source_events": "기존 라이브 이벤트 사례 · Top 100 Challenge / Golden Ducky",
        "source_tech": "UGC 지급·이벤트·유입 연계 시스템의 적용 사례",
        "source_ugc": "NNN GAMES UGC 제작 포트폴리오",
        "source_gettrain": "ZEPETO · Get Train · 프로젝트 기간 2024.09–2025.12",
        "source_proposal": "브랜드·IP 협업을 위한 제안 접근법",
        "title_intro": "회사소개",
        "title_metrics": "주요지표",
        "title_live-games": "운영게임",
        "title_game-design": "게임설계",
        "title_ugc-rewards": "UGC 보상",
        "title_ugc-creation": "UGC 제작",
        "title_live-operations": "라이브 운영",
        "title_technology": "보유기술",
        "title_development": "개발현황",
        "title_team": "팀소개",
        "title_partnerships": "협업사례",
        "title_ip-strategy": "IP 전략",
        "title_contact": "협업문의",
        "title_history": "회사연혁",
        "title_metric-details": "상세지표",
        "title_portfolio": "추가사례",
        "title_ip-proposal": "IP 제안",
        "intro_headline": "NNN GAMES",
        "cap_games": "게임 개발",
        "cap_ugc": "UGC 제작",
        "cap_live": "라이브 운영",
        "metric_projects": "운영 게임",
        "metric_visits": "게임 누적 방문",
        "metric_members": "커뮤니티 가입 합계",
        "metric_projects_note": "현재 집계 대상 게임",
        "metric_visits_note": "재방문을 포함한 방문 횟수",
        "metric_members_note": "7개 그룹 합계 · 그룹 간 중복 포함",
        "about_lead": "트리플엔게임즈는 자체 게임 개발과 라이브 운영을 중심으로, 브랜드·IP 게임과 UGC 콘텐츠를 제작하는 ROBLOX 전문 게임 스튜디오입니다.",
        "about_cap1_desc": "자체 ROBLOX 게임 및 브랜드/IP 기반 게임 기획 및 개발",
        "about_cap2_desc": "출시 이후 업데이트/이벤트/퀘스트/랭킹 지속 운영",
        "about_cap3_desc": "Free/Limited UGC를 게임 플레이와 보상 루프에 연결",
        "phase_build": "기획·개발",
        "phase_launch": "출시",
        "phase_operate": "운영",
        "phase_improve": "개선",
        "name_tower-flood-race": "Tower Flood Race",
        "genre_tower-flood-race": "멀티플레이 오비 레이스",
        "alt_tower-flood-race": "Tower Flood Race 게임 이미지",
        "name_tomato-splatter-simulator": "Tomato Splatter Simulator",
        "genre_tomato-splatter-simulator": "액션 · 성장 시뮬레이션",
        "alt_tomato-splatter-simulator": "Tomato Splatter Simulator 게임 이미지",
        "name_afk-or": "[Free UGC] AFK or arcade game",
        "genre_afk-or": "아케이드 · UGC 수집",
        "alt_afk-or": "[Free UGC] AFK or arcade game 게임 이미지",
        "name_free-ugc-rng": "FREE UGC RNG",
        "genre_free-ugc-rng": "RNG · UGC 수집",
        "alt_free-ugc-rng": "🎁 FREE UGC RNG 게임 이미지",
        "name_korean-spa": "Korean Spa",
        "genre_korean-spa": "퍼즐 · 탐험 어드벤처",
        "alt_korean-spa": "Korean Spa 게임 이미지",
        "name_fruit-battles": "Fruit Battles",
        "genre_fruit-battles": "실시간 아레나 PvP",
        "alt_fruit-battles": "Fruit Battles 게임 이미지",
        "design_tfr_desc": "물이 차오르는 타워에서 경쟁하고, 보상과 퀘스트로 다시 도전합니다.",
        "design_tomato_desc": "타격감 있는 액션에 자원 획득과 지속 성장을 결합합니다.",
        "step_race": "레이스",
        "step_compete": "순위 경쟁",
        "step_reward": "보상",
        "step_action": "타격",
        "step_resources": "자원 획득",
        "step_growth": "성장",
        "ugc_afk_desc": "미니게임과 AFK로 모은 코인을 무료 한정 UGC로 교환합니다.",
        "ugc_rng_desc": "더키를 수집하고 행운을 키우며, 코인으로 한정 UGC를 획득합니다.",
        "step_play": "플레이",
        "step_coins": "코인",
        "step_ugc": "UGC 교환",
        "step_collect": "수집",
        "step_luck": "행운 성장",
        "ugcworks_p1": "제작 난이도가 높은 고품질 UGC 제작",
        "ugcworks_p2": "다양한 부위와 소재, 애니메이션까지 제작",
        "ugcworks_p3": "게임과 연동한 UGC 판매 프로세스 구축",
        "creation_craft": "제작 품질",
        "creation_range": "다양한 표현",
        "creation_connect": "게임 연동",
        "creation_project": "NNN UGC · 아바타 아이템 제작·판매 프로젝트",
        "alt_ugc_item": "NNN GAMES 제작 UGC 아이템",
        "liveops_lead": "출시 이후의 운영까지 게임 개발의 일부로 봅니다.",
        "event_top100": "Top 100 Challenge",
        "event_ducky": "Golden Ducky",
        "event_top100_desc": "기간 한정 순위 경쟁과 한정 UGC 보상",
        "event_ducky_desc": "수집과 이벤트 보상을 연결한 참여 경험",
        "alt_event_top100": "2-Week Top 100 Challenge 이벤트 배너",
        "alt_event_ducky": "Golden Ducky Drop 이벤트 배너",
        "ops_quest": "퀘스트",
        "ops_ranking": "랭킹",
        "ops_rewards": "이벤트 보상",
        "ops_updates": "콘텐츠 개선",
        "tech_ugc_title": "UGC 자동 지급 및 관리 시스템",
        "tech_event_title": "자동 이벤트 운영 시스템",
        "tech_promo_title": "크로스 프로모션 시스템",
        "alt_tech_ugc": "UGC 자동 지급 관리자 대시보드 화면",
        "alt_tech_event_1": "라이브 이벤트 진행 화면",
        "alt_tech_event_2": "정기 랭킹 이벤트 배너",
        "alt_tech_promo": "게임 내 크로스 프로모션 팝업 화면",
        "tech_ugc_short": "퀘스트·포인트·랭킹과 연계한 UGC 지급 및 재고 관리",
        "tech_event_short": "기간과 주기에 맞춘 이벤트 시작·종료 및 보상 운영",
        "tech_promo_short": "운영 게임과 커뮤니티를 연결하는 플레이어 유입 관리",
        "name_enchanted-weapon": "Enchant a Weapon",
        "desc_enchanted-weapon": "무기 제작·강화와 UGC 보상을 결합한 RPG",
        "alt_enchanted-weapon": "Enchant a Weapon 개발 이미지",
        "name_asmr-ugc-town": "ASMR UGC Town",
        "desc_asmr-ugc-town": "ASMR 장애물 탐험과 재료 수집, 무료 UGC 교환",
        "alt_asmr-ugc-town": "ASMR UGC Town 개발 이미지",
        "name_hunt-a-slime": "Hunt a slime",
        "desc_hunt-a-slime": "슬라임을 찾아 떠나는 사냥 모험 콘셉트",
        "alt_hunt-a-slime": "Hunt a slime 개발 이미지",
        "name_tomato-splatter": "Tomato Splatter",
        "desc_tomato-splatter": "토마토가 터지는 농장의 캐주얼 액션 콘셉트",
        "alt_tomato-splatter": "Tomato Splatter 개발 이미지",
        "people_avatar_alt": "NNN GAMES 팀원 로블록스 아바타 — {{name}}",
        "global_desc1": "JR동일본, 네이버제트와 함께 진행한 도쿄 야마노테선을 배경으로 제작된 게임형 체험 프로젝트",
        "global_desc2": "JRE WALLET(블록체인 기반 전자지갑) 연동 이벤트 시스템 개발 및 운영",
        "alt_global_1": "Get Train 월드 플레이 화면",
        "alt_global_2": "Get Train × JRE WALLET 앱 연동 캠페인 배너",
        "alt_global_3": "Get Train × JRE WALLET 연동 5ZEM 증정 캠페인 배너",
        "alt_global_4": "Get Train 무료 위시 아이템 배너",
        "partner_world": "게임형 체험",
        "partner_integration": "외부 서비스 연동",
        "partner_operations": "이벤트 개발·운영",
        "partner_platform": "ZEPETO 프로젝트",
        "ip_intro": "IP 접점",
        "ip_intro_desc": "친숙한 장르로 캐릭터와 세계관을 전달",
        "ip_reward": "참여 목표",
        "ip_reward_desc": "게임 플레이와 UGC 보상을 연결",
        "ip_community": "커뮤니티",
        "ip_community_desc": "퀘스트·이벤트로 관계를 이어가기",
        "ip_expand": "목적별 확장",
        "ip_expand_desc": "브랜드 홍보·콘텐츠·온오프라인 이벤트",
        "ip_members_title": "NNN UGC 커뮤니티",
        "ip_members_label": "현재 그룹 가입 수",
        "ip_members_note": "게임·UGC와 연결된 커뮤니티의 현재 규모",
        "alt_community": "NNN UGC 커뮤니티 아이콘",
        "contact_game_desc": "게임 기획·개발",
        "contact_ip_desc": "브랜드·IP / UGC 콘텐츠",
        "contact_ops_desc": "출시 이후 운영",
        "contact_next": "목표 · 이용자 · 콘텐츠 범위 · 일정을 공유해 주세요.",
        "contact_rep": "대표 문의",
        "contact_general": "일반 협업 문의",
        "contact_site": "회사 홈페이지",
        "contact_address": "경기도 화성시 동탄구 동탄순환대로 878 (영천동), 311호",
        "history_era_mobile": "iOS와 Android 게임을 출시했습니다.",
        "history_era_ifland": "참여형 공간과 이벤트를 만들었습니다.",
        "history_era_zepeto": "Get Train 등 브랜드 월드를 만들고 운영했습니다.",
        "history_era_roblox_new": "게임·UGC 개발과 라이브 운영을 이어갑니다.",
        "history_present": "현재",
        "alt_history_mobile": "모바일 게임 제작 사례",
        "alt_history_ifland": "IFLAND 제작 사례",
        "alt_history_zepeto": "ZEPETO 제작 사례",
        "details_def_visits": "방문: 재방문을 포함한 누적 횟수",
        "details_def_members": "커뮤니티: 7개 그룹 가입 합계, 그룹 간 중복 포함",
        "details_total": "운영 게임 방문 합계",
        "portfolio_spa_desc": "작아진 탐험가가 거대한 한국 목욕탕을 탐험하는 퍼즐 어드벤처",
        "portfolio_fruit_desc": "과일 스킬·슬랩 액션·전리품 성장을 결합한 아레나 PvP",
        "kungya_expansion_brand_title": "브랜드·IP 홍보",
        "kungya_expansion_content_title": "수익형 게임 콘텐츠 제작",
        "kungya_expansion_events_title": "온오프라인 이벤트 연동",
        "alt_kungya_expansion_brand": "브랜드·IP 홍보 소재 예시 화면",
        "alt_kungya_expansion_content": "수익화 게임 콘텐츠 예시 화면",
        "alt_kungya_expansion_events": "온오프라인 연계 이벤트 예시 화면",
        "proposal_brand_desc": "캐릭터·세계관을 담은 플레이와 UGC 접점",
        "proposal_content_desc": "게임·UGC 콘텐츠의 제작·운영 구조 설계",
        "proposal_event_desc": "게임 안의 참여를 온라인·오프라인 경험으로 연결",
        "brief_goal": "목표",
        "brief_audience": "이용자",
        "brief_ip": "IP·소재",
        "brief_scope": "일정·범위"
    },
    "en": {
        "ui_page_title": "NNN GAMES Company Introduction",
        "ui_prev": "Prev",
        "ui_next": "Next",
        "ui_lang_group": "Select language",
        "ui_fullscreen": "Fullscreen",
        "ui_fullscreen_exit": "Exit fullscreen",
        "ui_deck_label": "NNN GAMES company introduction slides",
        "ui_dot": "Go to slide {{n}}",
        "ui_dot_appendix": "Go to appendix slide {{n}}",
        "ui_slide_position": "Slide {{current}} of {{total}}",
        "ui_appendix": "Appendix",
        "ui_appendix_position": "Appendix {{current}} of {{total}}",
        "ui_slide_navigation": "Select slide",
        "meta_draft": "Company introduction · 2026.10",
        "label_appendix": "Appendix",
        "label_visits": "Total visits",
        "label_favorites": "Favorites",
        "label_rating": "Like ratio",
        "label_launch": "Launch month",
        "label_game": "Game",
        "label_current": "Live",
        "label_development": "In development",
        "label_concept": "Development concept",
        "label_expected": "Expected release",
        "label_production": "UGC creation project",
        "source_current": "Roblox public metrics · 2026.10.01 14:57 KST",
        "source_games": "6 live games · Roblox public metrics · 2026.10.01",
        "source_pipeline": "In development · Scheduled release months · 2026.10",
        "source_cases": "Gameplay and reward design from live games",
        "source_events": "Past live events · Top 100 Challenge / Golden Ducky",
        "source_tech": "UGC distribution, events and cross-promotion examples",
        "source_ugc": "NNN GAMES UGC creation portfolio",
        "source_gettrain": "ZEPETO · Get Train · Project period 2024.09–2025.12",
        "source_proposal": "Proposed approach for brand and IP partnerships",
        "title_intro": "Company",
        "title_metrics": "Key Metrics",
        "title_live-games": "Live Games",
        "title_game-design": "Game Design",
        "title_ugc-rewards": "UGC Rewards",
        "title_ugc-creation": "UGC Creation",
        "title_live-operations": "Live Operations",
        "title_technology": "Core Technology",
        "title_development": "Development",
        "title_team": "Our Team",
        "title_partnerships": "Partnerships",
        "title_ip-strategy": "IP Strategy",
        "title_contact": "Contact",
        "title_history": "History",
        "title_metric-details": "Metrics",
        "title_portfolio": "Portfolio",
        "title_ip-proposal": "IP Proposal",
        "intro_headline": "NNN GAMES",
        "cap_games": "Game development",
        "cap_ugc": "UGC creation",
        "cap_live": "Live operations",
        "metric_projects": "Live games",
        "metric_visits": "Total game visits",
        "metric_members": "Community memberships",
        "metric_projects_note": "Games included in the current total",
        "metric_visits_note": "Visits include repeat visits",
        "metric_members_note": "Sum across 7 groups · Includes overlap",
        "about_lead": "Triple N Games is a ROBLOX-focused studio built around in-house game development and live operations, producing brand/IP titles and UGC content.",
        "about_cap1_desc": "Planning and development of in-house ROBLOX titles and brand/IP-based games",
        "about_cap2_desc": "Ongoing updates, events, quests, and rankings after launch",
        "about_cap3_desc": "Connecting Free/Limited UGC to gameplay and reward loops",
        "phase_build": "Build",
        "phase_launch": "Launch",
        "phase_operate": "Operate",
        "phase_improve": "Improve",
        "name_tower-flood-race": "Tower Flood Race",
        "genre_tower-flood-race": "Multiplayer obby race",
        "alt_tower-flood-race": "Tower Flood Race game image",
        "name_tomato-splatter-simulator": "Tomato Splatter Simulator",
        "genre_tomato-splatter-simulator": "Action / progression simulation",
        "alt_tomato-splatter-simulator": "Tomato Splatter Simulator game image",
        "name_afk-or": "[Free UGC] AFK or arcade game",
        "genre_afk-or": "Arcade / UGC collection",
        "alt_afk-or": "[Free UGC] AFK or arcade game game image",
        "name_free-ugc-rng": "FREE UGC RNG",
        "genre_free-ugc-rng": "RNG / UGC collection",
        "alt_free-ugc-rng": "🎁 FREE UGC RNG game image",
        "name_korean-spa": "Korean Spa",
        "genre_korean-spa": "Puzzle / exploration adventure",
        "alt_korean-spa": "Korean Spa game image",
        "name_fruit-battles": "Fruit Battles",
        "genre_fruit-battles": "Real-time arena PvP",
        "alt_fruit-battles": "Fruit Battles game image",
        "design_tfr_desc": "Race up a flooding tower, then return for rewards and quests.",
        "design_tomato_desc": "Combine satisfying action with resource collection and progression.",
        "step_race": "Race",
        "step_compete": "Compete",
        "step_reward": "Rewards",
        "step_action": "Action",
        "step_resources": "Resources",
        "step_growth": "Progress",
        "ugc_afk_desc": "Exchange coins earned through mini-games and AFK play for free limited UGC.",
        "ugc_rng_desc": "Collect Duckies, grow your luck and redeem coins for limited UGC.",
        "step_play": "Play",
        "step_coins": "Coins",
        "step_ugc": "Redeem UGC",
        "step_collect": "Collect",
        "step_luck": "Grow luck",
        "ugcworks_p1": "High-difficulty, high-quality UGC production",
        "ugcworks_p2": "Every body slot and material — animation included",
        "ugcworks_p3": "A UGC sales pipeline wired into our games",
        "creation_craft": "Craft",
        "creation_range": "Range",
        "creation_connect": "Integration",
        "creation_project": "NNN UGC · Avatar item creation and sales project",
        "alt_ugc_item": "UGC item created by NNN GAMES",
        "liveops_lead": "We treat post-launch operations as part of game development.",
        "event_top100": "Top 100 Challenge",
        "event_ducky": "Golden Ducky",
        "event_top100_desc": "Timed ranking competition and limited UGC rewards",
        "event_ducky_desc": "An event connecting collection and rewards",
        "alt_event_top100": "2-Week Top 100 Challenge event banner",
        "alt_event_ducky": "Golden Ducky Drop event banner",
        "ops_quest": "Quests",
        "ops_ranking": "Rankings",
        "ops_rewards": "Event rewards",
        "ops_updates": "Content updates",
        "tech_ugc_title": "Automated UGC grant & management system",
        "tech_event_title": "Automated event operations system",
        "tech_promo_title": "Cross-promotion system",
        "alt_tech_ugc": "UGC auto-grant admin dashboard screen",
        "alt_tech_event_1": "Live event in progress",
        "alt_tech_event_2": "Recurring ranking event banner",
        "alt_tech_promo": "In-game cross-promotion popup screen",
        "tech_ugc_short": "UGC distribution and inventory linked to quests, points and rankings",
        "tech_event_short": "Event scheduling and rewards based on periods and intervals",
        "tech_promo_short": "Player acquisition across live games and communities",
        "name_enchanted-weapon": "Enchant a Weapon",
        "desc_enchanted-weapon": "An RPG combining weapon crafting, enhancement and UGC rewards",
        "alt_enchanted-weapon": "Enchant a Weapon development visual",
        "name_asmr-ugc-town": "ASMR UGC Town",
        "desc_asmr-ugc-town": "ASMR obstacles, material collection and free UGC exchange",
        "alt_asmr-ugc-town": "ASMR UGC Town development visual",
        "name_hunt-a-slime": "Hunt a slime",
        "desc_hunt-a-slime": "A hunting adventure concept about discovering slimes",
        "alt_hunt-a-slime": "Hunt a slime development visual",
        "name_tomato-splatter": "Tomato Splatter",
        "desc_tomato-splatter": "A casual action concept on a farm bursting with tomatoes",
        "alt_tomato-splatter": "Tomato Splatter development visual",
        "people_avatar_alt": "NNN GAMES team member Roblox avatar — {{name}}",
        "global_desc1": "A game-style experience project set on Tokyo's Yamanote Line, produced with JR East and NAVER Z",
        "global_desc2": "Development and operation of an event system integrated with JRE WALLET (a blockchain-based wallet)",
        "alt_global_1": "Get Train world gameplay screenshot",
        "alt_global_2": "Get Train × JRE WALLET app-linking campaign banner",
        "alt_global_3": "Get Train × JRE WALLET 5ZEM giveaway campaign banner",
        "alt_global_4": "Get Train free wish item banner",
        "partner_world": "Game experience",
        "partner_integration": "Service integration",
        "partner_operations": "Event operations",
        "partner_platform": "ZEPETO project",
        "ip_intro": "Introduce",
        "ip_intro_desc": "Introduce characters and worlds through familiar genres",
        "ip_reward": "Engage",
        "ip_reward_desc": "Connect gameplay with UGC rewards",
        "ip_community": "Community",
        "ip_community_desc": "Maintain engagement through quests and events",
        "ip_expand": "Expand",
        "ip_expand_desc": "Brand promotion, content and online / offline events",
        "ip_members_title": "NNN UGC community",
        "ip_members_label": "Current group memberships",
        "ip_members_note": "Current size of a community connected to games and UGC",
        "alt_community": "NNN UGC community icon",
        "contact_game_desc": "Game planning and development",
        "contact_ip_desc": "Brand / IP and UGC content",
        "contact_ops_desc": "Post-launch operations",
        "contact_next": "Share your goals, audience, content scope and schedule.",
        "contact_rep": "CEO contact",
        "contact_general": "Partnership inquiries",
        "contact_site": "Company website",
        "contact_address": "311, 878 Dongtansunhwan-daero, Dongtan-gu, Hwaseong-si, Gyeonggi-do, Republic of Korea",
        "history_era_mobile": "Shipped games on iOS and Android.",
        "history_era_ifland": "Created interactive spaces and events.",
        "history_era_zepeto": "Built and operated branded worlds, including Get Train.",
        "history_era_roblox_new": "Game and UGC development with live operations.",
        "history_present": "Present",
        "alt_history_mobile": "Mobile game portfolio",
        "alt_history_ifland": "IFLAND portfolio",
        "alt_history_zepeto": "ZEPETO portfolio",
        "details_def_visits": "Visits: cumulative visits including repeat visits",
        "details_def_members": "Community: membership sum across 7 groups, including overlap",
        "details_total": "Total live-game visits",
        "portfolio_spa_desc": "A puzzle adventure exploring a giant Korean spa as a tiny explorer",
        "portfolio_fruit_desc": "Arena PvP combining fruit skills, slap combat and loot-driven progression",
        "kungya_expansion_brand_title": "Brand & IP promotion",
        "kungya_expansion_content_title": "Build monetizable game content",
        "kungya_expansion_events_title": "Connect online & offline events",
        "alt_kungya_expansion_brand": "Example brand & IP promotional material",
        "alt_kungya_expansion_content": "Example monetized game content screenshot",
        "alt_kungya_expansion_events": "Example online-offline linked event screen",
        "proposal_brand_desc": "Play and UGC touchpoints built around characters and worlds",
        "proposal_content_desc": "Design the creation and operations model for game and UGC content",
        "proposal_event_desc": "Connect in-game participation to online and offline experiences",
        "brief_goal": "Goals",
        "brief_audience": "Audience",
        "brief_ip": "IP / theme",
        "brief_scope": "Schedule / scope"
    },
    "ja": {
        "ui_page_title": "NNN GAMES 会社紹介",
        "ui_prev": "前へ",
        "ui_next": "次へ",
        "ui_lang_group": "言語を選択",
        "ui_fullscreen": "全画面表示",
        "ui_fullscreen_exit": "全画面表示を終了",
        "ui_deck_label": "NNN GAMES 会社紹介スライド",
        "ui_dot": "スライド{{n}}へ移動",
        "ui_dot_appendix": "付録スライド{{n}}へ移動",
        "ui_slide_position": "{{total}}枚中{{current}}枚目",
        "ui_appendix": "付録",
        "ui_appendix_position": "付録 {{current}} / {{total}}",
        "ui_slide_navigation": "スライドを選択",
        "meta_draft": "会社紹介 · 2026.10",
        "label_appendix": "付録",
        "label_visits": "累計訪問数",
        "label_favorites": "お気に入り",
        "label_rating": "高評価率",
        "label_launch": "公開月",
        "label_game": "ゲーム",
        "label_current": "運営中",
        "label_development": "開発中",
        "label_concept": "開発コンセプト",
        "label_expected": "公開予定",
        "label_production": "UGC制作プロジェクト",
        "source_current": "Roblox公開指標 · 2026.10.01 14:57 KST",
        "source_games": "運営ゲーム6本 · Roblox公開指標 · 2026.10.01",
        "source_pipeline": "開発中 · 登録済み公開予定月 · 2026.10",
        "source_cases": "運営ゲームのプレイ・報酬設計事例",
        "source_events": "過去のライブイベント事例 · Top 100 Challenge / Golden Ducky",
        "source_tech": "UGC配布・イベント・相互送客システムの適用例",
        "source_ugc": "NNN GAMES UGC制作ポートフォリオ",
        "source_gettrain": "ZEPETO · Get Train · プロジェクト期間 2024.09–2025.12",
        "source_proposal": "ブランド・IP協業に向けた提案アプローチ",
        "title_intro": "会社紹介",
        "title_metrics": "主な実績",
        "title_live-games": "運営ゲーム",
        "title_game-design": "ゲーム設計",
        "title_ugc-rewards": "UGC報酬",
        "title_ugc-creation": "UGC制作",
        "title_live-operations": "ライブ運営",
        "title_technology": "保有技術",
        "title_development": "開発状況",
        "title_team": "チーム紹介",
        "title_partnerships": "協業事例",
        "title_ip-strategy": "IP戦略",
        "title_contact": "協業相談",
        "title_history": "会社沿革",
        "title_metric-details": "詳細指標",
        "title_portfolio": "追加事例",
        "title_ip-proposal": "IP提案",
        "intro_headline": "NNN GAMES",
        "cap_games": "ゲーム開発",
        "cap_ugc": "UGC制作",
        "cap_live": "ライブ運営",
        "metric_projects": "運営ゲーム",
        "metric_visits": "ゲーム累計訪問数",
        "metric_members": "コミュニティ加入数合計",
        "metric_projects_note": "現在の集計対象ゲーム",
        "metric_visits_note": "再訪問を含む訪問回数",
        "metric_members_note": "7グループの合計 · グループ間の重複を含む",
        "about_lead": "トリプルエヌゲームズは、自社ゲーム開発とライブ運営を軸に、ブランド・IPゲームとUGCコンテンツを制作するROBLOX専門ゲームスタジオです。",
        "about_cap1_desc": "自社ROBLOXゲームおよびブランド/IPベースゲームの企画・開発",
        "about_cap2_desc": "リリース後のアップデート/イベント/クエスト/ランキングの継続運営",
        "about_cap3_desc": "Free/Limited UGCをゲームプレイと報酬ループに接続",
        "phase_build": "企画・開発",
        "phase_launch": "公開",
        "phase_operate": "運営",
        "phase_improve": "改善",
        "name_tower-flood-race": "Tower Flood Race",
        "genre_tower-flood-race": "マルチプレイObbyレース",
        "alt_tower-flood-race": "Tower Flood Raceのゲーム画像",
        "name_tomato-splatter-simulator": "Tomato Splatter Simulator",
        "genre_tomato-splatter-simulator": "アクション・成長シミュレーション",
        "alt_tomato-splatter-simulator": "Tomato Splatter Simulatorのゲーム画像",
        "name_afk-or": "[Free UGC] AFK or arcade game",
        "genre_afk-or": "アーケード・UGC収集",
        "alt_afk-or": "[Free UGC] AFK or arcade gameのゲーム画像",
        "name_free-ugc-rng": "FREE UGC RNG",
        "genre_free-ugc-rng": "RNG・UGC収集",
        "alt_free-ugc-rng": "🎁 FREE UGC RNGのゲーム画像",
        "name_korean-spa": "Korean Spa",
        "genre_korean-spa": "パズル・探索アドベンチャー",
        "alt_korean-spa": "Korean Spaのゲーム画像",
        "name_fruit-battles": "Fruit Battles",
        "genre_fruit-battles": "リアルタイムアリーナPvP",
        "alt_fruit-battles": "Fruit Battlesのゲーム画像",
        "design_tfr_desc": "水位が上がるタワーで競い、報酬とクエストで再び挑戦します。",
        "design_tomato_desc": "爽快なアクションに資源獲得と継続的な成長を組み合わせます。",
        "step_race": "レース",
        "step_compete": "順位を競う",
        "step_reward": "報酬",
        "step_action": "攻撃",
        "step_resources": "資源獲得",
        "step_growth": "成長",
        "ugc_afk_desc": "ミニゲームと放置で貯めたコインを無料の限定UGCと交換します。",
        "ugc_rng_desc": "ダッキーを集めて運を育て、コインで限定UGCを獲得します。",
        "step_play": "プレイ",
        "step_coins": "コイン",
        "step_ugc": "UGC交換",
        "step_collect": "収集",
        "step_luck": "運を育てる",
        "ugcworks_p1": "制作難易度の高い高品質UGCを制作",
        "ugcworks_p2": "多様な部位と素材、アニメーションまで制作",
        "ugcworks_p3": "ゲームと連動したUGC販売プロセスを構築",
        "creation_craft": "制作品質",
        "creation_range": "多様な表現",
        "creation_connect": "ゲーム連携",
        "creation_project": "NNN UGC · アバターアイテム制作・販売プロジェクト",
        "alt_ugc_item": "NNN GAMES制作のUGCアイテム",
        "liveops_lead": "リリース後の運営までをゲーム開発の一部と捉えています。",
        "event_top100": "Top 100 Challenge",
        "event_ducky": "Golden Ducky",
        "event_top100_desc": "期間限定の順位競争と限定UGC報酬",
        "event_ducky_desc": "収集とイベント報酬をつなぐ参加体験",
        "alt_event_top100": "2-Week Top 100 Challenge イベントバナー",
        "alt_event_ducky": "Golden Ducky Drop イベントバナー",
        "ops_quest": "クエスト",
        "ops_ranking": "ランキング",
        "ops_rewards": "イベント報酬",
        "ops_updates": "コンテンツ改善",
        "tech_ugc_title": "UGC自動支給・管理システム",
        "tech_event_title": "自動イベント運営システム",
        "tech_promo_title": "クロスプロモーションシステム",
        "alt_tech_ugc": "UGC自動支給管理者ダッシュボード画面",
        "alt_tech_event_1": "ライブイベント進行画面",
        "alt_tech_event_2": "定期ランキングイベントバナー",
        "alt_tech_promo": "ゲーム内クロスプロモーションポップアップ画面",
        "tech_ugc_short": "クエスト・ポイント・ランキングに連動したUGC配布と在庫管理",
        "tech_event_short": "期間と周期に合わせたイベント開始・終了と報酬運営",
        "tech_promo_short": "運営ゲームとコミュニティをつなぐプレイヤー流入管理",
        "name_enchanted-weapon": "Enchant a Weapon",
        "desc_enchanted-weapon": "武器制作・強化とUGC報酬を組み合わせたRPG",
        "alt_enchanted-weapon": "Enchant a Weaponの開発ビジュアル",
        "name_asmr-ugc-town": "ASMR UGC Town",
        "desc_asmr-ugc-town": "ASMR障害物の探索・素材収集・無料UGC交換",
        "alt_asmr-ugc-town": "ASMR UGC Townの開発ビジュアル",
        "name_hunt-a-slime": "Hunt a slime",
        "desc_hunt-a-slime": "スライムを探す狩りの冒険コンセプト",
        "alt_hunt-a-slime": "Hunt a slimeの開発ビジュアル",
        "name_tomato-splatter": "Tomato Splatter",
        "desc_tomato-splatter": "トマトがはじける農場のカジュアルアクションコンセプト",
        "alt_tomato-splatter": "Tomato Splatterの開発ビジュアル",
        "people_avatar_alt": "NNN GAMESチームメンバーのRobloxアバター — {{name}}",
        "global_desc1": "JR東日本、NAVER Zと共に進めた、東京・山手線を舞台にしたゲーム型体験プロジェクト",
        "global_desc2": "JRE WALLET（ブロックチェーン基盤の電子ウォレット）連携イベントシステムの開発・運営",
        "alt_global_1": "Get Train ワールドのプレイ画面",
        "alt_global_2": "Get Train × JRE WALLET アプリ連携キャンペーンバナー",
        "alt_global_3": "Get Train × JRE WALLET 連携 5ZEM プレゼントキャンペーンバナー",
        "alt_global_4": "Get Train 無料ウィッシュアイテムバナー",
        "partner_world": "ゲーム型体験",
        "partner_integration": "外部サービス連携",
        "partner_operations": "イベント開発・運営",
        "partner_platform": "ZEPETOプロジェクト",
        "ip_intro": "IPとの接点",
        "ip_intro_desc": "親しみあるジャンルでキャラクターと世界観を伝える",
        "ip_reward": "参加目標",
        "ip_reward_desc": "ゲームプレイとUGC報酬をつなぐ",
        "ip_community": "コミュニティ",
        "ip_community_desc": "クエスト・イベントで関係をつなぐ",
        "ip_expand": "目的別の展開",
        "ip_expand_desc": "ブランドPR・コンテンツ・オンライン／オフラインイベント",
        "ip_members_title": "NNN UGCコミュニティ",
        "ip_members_label": "現在のグループ加入数",
        "ip_members_note": "ゲーム・UGCにつながるコミュニティの現在の規模",
        "alt_community": "NNN UGCコミュニティアイコン",
        "contact_game_desc": "ゲーム企画・開発",
        "contact_ip_desc": "ブランド・IP／UGCコンテンツ",
        "contact_ops_desc": "公開後の運営",
        "contact_next": "目標・対象ユーザー・コンテンツの範囲・日程をお聞かせください。",
        "contact_rep": "代表へのお問い合わせ",
        "contact_general": "協業のお問い合わせ",
        "contact_site": "会社サイト",
        "contact_address": "〒18469 韓国 京畿道 華城市 東灘区 東灘循環大路878 東灘ITタワー 311号室",
        "history_era_mobile": "iOS・Android向けゲームをリリース。",
        "history_era_ifland": "参加型スペースとイベントを制作。",
        "history_era_zepeto": "Get Trainを含むブランドワールドを開発・運営。",
        "history_era_roblox_new": "ゲーム・UGC開発とライブ運営に取り組んでいます。",
        "history_present": "現在",
        "alt_history_mobile": "モバイルゲーム制作事例",
        "alt_history_ifland": "IFLAND制作事例",
        "alt_history_zepeto": "ZEPETO制作事例",
        "details_def_visits": "訪問数：再訪問を含む累計回数",
        "details_def_members": "コミュニティ：7グループの加入数合計、グループ間の重複を含む",
        "details_total": "運営ゲーム訪問数合計",
        "portfolio_spa_desc": "小さな探検家として巨大な韓国式スパを探索するパズルアドベンチャー",
        "portfolio_fruit_desc": "フルーツスキル・スラップアクション・戦利品による成長を組み合わせたアリーナPvP",
        "kungya_expansion_brand_title": "ブランド・IPプロモーション",
        "kungya_expansion_content_title": "収益型ゲームコンテンツ制作",
        "kungya_expansion_events_title": "オン・オフラインイベント連携",
        "alt_kungya_expansion_brand": "ブランド・IPプロモーション素材の例示画面",
        "alt_kungya_expansion_content": "収益化ゲームコンテンツの例示画面",
        "alt_kungya_expansion_events": "オン・オフライン連携イベントの例示画面",
        "proposal_brand_desc": "キャラクター・世界観を反映したプレイとUGCの接点",
        "proposal_content_desc": "ゲーム・UGCコンテンツの制作・運営構造を設計",
        "proposal_event_desc": "ゲーム内の参加をオンライン・オフライン体験につなぐ",
        "brief_goal": "目標",
        "brief_audience": "ユーザー",
        "brief_ip": "IP・素材",
        "brief_scope": "日程・範囲"
    }
};
